# Generated by Django 5.0.6 on 2024-07-17 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypeApp', '0003_cat_in_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='cats/'),
        ),
        migrations.CreateModel(
            name='CommunityCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat_img', models.ImageField(default=None, upload_to='community_cats/')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('last_seen', models.TextField()),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
