# Generated by Django 5.0.6 on 2024-07-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototypeApp', '0005_thread_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='thread',
        ),
    ]
