# Generated by Django 5.0.6 on 2024-08-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypeApp', '0007_remove_comment_parent_alter_thread_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycat',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
