# Generated by Django 5.0.6 on 2024-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypeApp', '0008_alter_communitycat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycat',
            name='description',
            field=models.TextField(),
        ),
    ]
