# Generated by Django 5.0.6 on 2024-08-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypeApp', '0009_alter_communitycat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycat',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
